"""add phone number

Revision ID: 7027c326363f
Revises: dbef46ac488e
Create Date: 2023-04-04 23:49:13.934770

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7027c326363f'
down_revision = 'dbef46ac488e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_number', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone_number')
    # ### end Alembic commands ###
